### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by ggang-b** [prodzpod/NemesisRisingTides#1]
Hi, I was enjoying the risingtides mode you created, but I want to add a translation in Korean.
I'm not used to github, so I'm sorry to post it on the issues tab. ㅜㅜ
[ko language.txt](https://github.com/prodzpod/NemesisRisingTides/files/12928423/ko.language.txt)

**Comment by prodzpod** [comment]
ㄳ합니다 (내일 버그수정이랑 같이 업뎃함)
