### ISSUE TITLE
Magnetic Elites seem to cause ice explosions to detonate 20+ times at once

### ISSUE THREAD

**Issue by ImDolos** [prodzpod/NemesisRisingTides#2]
I've been having some issues with ice elites (and thunder elites, once) having their effects turn into instant kill thermonuclear bombs recently. I checked the error logs and it seems to be related to magnetic elites, it may only be happening when they detonate in a magnetic field, but I'm not sure. 
![ice_error](https://github.com/prodzpod/NemesisRisingTides/assets/149831315/7a0e477c-5a8d-40e9-aa13-343394975675)

**Comment by prodzpod** [comment]
cannot reproduce, check if there is other incompatibilities

**Comment by goldenguy00** [comment]
[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.GameObject.GetComponent[T] () (at <a20b3695b7ce4017b7981f9d06962bd1>:IL_0021)
NemesisRisingTides.Changes.Magnetic+<>c.<Init>b__12_2 (On.RoR2.GlobalEventManager+orig_OnHitEnemy orig, RoR2.GlobalEventManager self, RoR2.DamageInfo damageInfo, UnityEngine.GameObject _victim) (at <da187fc7503a49c0aa51eb7ff1775228>:IL_000B)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.GlobalEventManager::OnHitEnemy>?558519676(RoR2.GlobalEventManager,RoR2.DamageInfo,UnityEngine.GameObject)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.GlobalEventManager::OnHitEnemy>?-684977994(RoR2.GlobalEventManager,RoR2.DamageInfo,UnityEngine.GameObject)
NemesisSpikestrip.Changes.Veiled+<>c.<Init>b__6_5 (On.RoR2.GlobalEventManager+orig_OnHitEnemy orig, RoR2.GlobalEventManager self, RoR2.DamageInfo damageInfo, UnityEngine.GameObject _victim) (at <39ede942e7d044e293853e2fa2b0da18>:IL_006B)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.GlobalEventManager::OnHitEnemy>?555331436(RoR2.GlobalEventManager,RoR2.DamageInfo,UnityEngine.GameObject)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.GlobalEventManager::OnHitEnemy>?-665134574(RoR2.GlobalEventManager,RoR2.DamageInfo,UnityEngine.GameObject)
SS2.AttackerOverrideManager.OverrideOnHitEnemy (On.RoR2.GlobalEventManager+orig_OnHitEnemy orig, RoR2.GlobalEventManager self, RoR2.DamageInfo damageInfo, UnityEngine.GameObject victim) (at <cf719a4ae0604dea853a05835a392545>:IL_006C)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.GlobalEventManager::OnHitEnemy>?-2052716032(RoR2.GlobalEventManager,RoR2.DamageInfo,UnityEngine.GameObject)
(wrapper dynamic-method) RoR2.BlastAttack.DMD<RoR2.BlastAttack::PerformDamageServer>(RoR2.BlastAttack/BlastAttackDamageInfo&)
(wrapper dynamic-method) RoR2.BlastAttack.DMD<RoR2.BlastAttack::HandleHits>(RoR2.BlastAttack,RoR2.BlastAttack/HitPoint[])
RoR2.BlastAttack.Fire () (at <a149dbd7438a4e73b97d6600b3a2bbd4>:IL_0007)
(wrapper dynamic-method) RoR2.DelayBlast.DMD<RoR2.DelayBlast::Detonate>(RoR2.DelayBlast)
RoR2.DelayBlast.FixedUpdate () (at <a149dbd7438a4e73b97d6600b3a2bbd4>:IL_009F)

**Comment by goldenguy00** [comment]
still happening. this bug has been around for as long as i can remember

**Comment by goldenguy00** [comment]
CharacterBody attacker = damageInfo.attacker?.GetComponent<CharacterBody>();

im guessing its due to unity not liking ?. cuz everything else looks ok?

edit: could be that you dont nullcheck attacker.master before doing 
                        attacker.master.money += (uint)(stealCount * GainMoneyAmount.Value);

**Comment by prodzpod** [comment]
i had to get hit
